# Generated by Django 2.2.5 on 2019-09-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', models.CharField(choices=[('main', 'Main'), ('col1', 'Column 1'), ('col2', 'Column 2')], default='main', max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Text',
            new_name='HomeText',
        ),
    ]
