# Generated by Django 2.2.5 on 2019-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190915_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttext',
            name='position',
            field=models.CharField(choices=[('main', 'Main'), ('main1', 'Main 1'), ('main2', 'Main 2'), ('col1', 'Column 1'), ('col2', 'Column 2')], default='main', max_length=5),
        ),
    ]
